name: kadastr
description: "Kadastr — Flutter starter."
publish_to: 'none'
version: 1.0.0+3

environment:
  sdk: ^3.10.1

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.10+1
  flutter_native_splash: ^2.4.3
  photo_view: ^0.15.0
  shared_preferences: ^2.5.5
  share_plus: ^10.1.4
  image_picker: ^1.1.2
  http: ^1.2.2
  model_viewer_plus: ^1.10.0
  path_provider: ^2.1.5
  flutter_map: ^7.0.2
  latlong2: ^0.9.1
  geolocator: ^13.0.2
  flutter_staggered_grid_view: ^0.7.0
  url_launcher: ^6.3.0
  in_app_review: ^2.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.1

flutter:
  uses-material-design: true

  assets:
    - assets/3d/
    - assets/branding/
    - assets/branding/splash/
    - assets/icons/
    - assets/images/
    - assets/images/auth/
    - assets/images/flags/
    - assets/images/home/
    - assets/images/payment/
    - assets/images/services/

  fonts:
    - family: MTSCompact
      fonts:
        - asset: assets/fonts/MTSCompact-Regular.ttf
        - asset: assets/fonts/MTSCompact-Medium.ttf
          weight: 500
        - asset: assets/fonts/MTSCompact-Bold.ttf
          weight: 700
        - asset: assets/fonts/MTSCompact-Black.ttf
          weight: 900
    - family: MTSText
      fonts:
        - asset: assets/fonts/MTSText-Regular.ttf
        - asset: assets/fonts/MTSText-Medium.ttf
          weight: 500
        - asset: assets/fonts/MTSText-Bold.ttf
          weight: 700
        - asset: assets/fonts/MTSText-Black.ttf
          weight: 900

flutter_launcher_icons:
  android: "ic_launcher"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/branding/appicon.png"
  min_sdk_android: 21
  adaptive_icon_background: "#034112"
  adaptive_icon_foreground: "assets/branding/appicon.png"

flutter_native_splash:
  color: "#00E135"
  image: "assets/branding/appicon.png"
  android_12:
    color: "#00E135"
    image: "assets/branding/appicon.png"
  android: true
  ios: true
  web: false
